// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBridge.Data;

#nullable disable

namespace TicketBridge.Migrations.TicketBridge
{
    [DbContext(typeof(TicketBridgeContext))]
    [Migration("20241211142006_sqlite.local_migration_687")]
    partial class sqlitelocal_migration_687
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TicketBridge.Client.Models.GitHubIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GitHubIntegrations");
                });
#pragma warning restore 612, 618
        }
    }
}
